// Generated by @nuxtjs/sanity
export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroTitle: string;
  heroDescription: string;
  heroVideoId: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Proyecto = {
  _id: string;
  _type: "proyecto";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  location: string;
  date?: string;
  areaConstruida?: number;
  categories?: Array<string>;
  additionalDetails?: Array<{
    label?: string;
    value?: string;
    _type: "detail";
    _key: string;
  }>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  videoUrl?: string;
  fechaPublicacion: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Publicacion = {
  _id: string;
  _type: "publicacion";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo: string;
  slug: Slug;
  fechaPublicacion: string;
  imagen?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  contenido: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    _type: "image";
    _key: string;
  }>;
  extracto?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Home | SanityImageAssetReference | Proyecto | SanityImageCrop | SanityImageHotspot | Slug | Publicacion | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: app/components/PostSection.vue
// Variable: postsQuery
// Query: *[    _type == "publicacion"    && defined(slug.current)  ]|order(fechaPublicacion desc)[0...3]{titulo, slug, fechaPublicacion, imagen, extracto}
export type PostsQueryResult = Array<{
  titulo: string;
  slug: Slug;
  fechaPublicacion: string;
  imagen: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  extracto: string | null;
}>;

// Source: app/components/ProjectSection.vue
// Variable: projectsQuery
// Query: *[    _type == "proyecto"]|order(date desc)[0...3]{_id, title, slug, location, gallery}
export type ProjectsQueryResult = Array<{
  _id: string;
  title: string;
  slug: Slug;
  location: string;
  gallery: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }> | null;
}>;

// Source: app/pages/blog/[slug].vue
// Variable: query
// Query: *[_type == "publicacion" && slug.current == $slug][0] {  _id,  titulo,  contenido,  slug,  fechaPublicacion,  imagen}
export type QueryResult = {
  _id: string;
  titulo: string;
  contenido: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    _type: "image";
    _key: string;
  }>;
  slug: Slug;
  fechaPublicacion: string;
  imagen: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;

// Source: app/pages/blog/index.vue
// Variable: queryPosts
// Query: *[_type == "publicacion" && defined(slug.current) && (  $lastDate == null ||   fechaPublicacion < $lastDate ||   (fechaPublicacion == $lastDate && _id < $lastId))]|order(fechaPublicacion desc, _id desc)[0...$limit]{  _id,  titulo,  slug,  fechaPublicacion,  imagen,  extracto}
export type QueryPostsResult = Array<{
  _id: string;
  titulo: string;
  slug: Slug;
  fechaPublicacion: string;
  imagen: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  extracto: string | null;
}>;

// Source: app/pages/proyectos/[slug].vue
// Variable: queryProject
// Query: *[_type == "proyecto" && slug.current == $slug][0]{  _id,  title,  location,  description,  date,  categories,  gallery,  videoUrl}
export type QueryProjectResult = {
  _id: string;
  title: string;
  location: string;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  date: string | null;
  categories: Array<string> | null;
  gallery: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }> | null;
  videoUrl: string | null;
} | null;

// Source: app/pages/proyectos/index.vue
// Variable: queryProjects
// Query: *[_type == "proyecto" && (  $lastDate == null ||   fechaPublicacion < $lastDate ||   (fechaPublicacion == $lastDate && _id < $lastId))]|order(fechaPublicacion desc, _id desc)[0...$limit]{  _id,  title,  slug,  location,  date,  gallery,  fechaPublicacion}
export type QueryProjectsResult = Array<{
  _id: string;
  title: string;
  slug: Slug;
  location: string;
  date: string | null;
  gallery: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }> | null;
  fechaPublicacion: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[\n    _type == \"publicacion\"\n    && defined(slug.current)\n  ]|order(fechaPublicacion desc)[0...3]{titulo, slug, fechaPublicacion, imagen, extracto}": PostsQueryResult;
    "*[\n    _type == \"proyecto\"\n]|order(date desc)[0...3]{_id, title, slug, location, gallery}": ProjectsQueryResult;
    "*[_type == \"publicacion\" && slug.current == $slug][0] {\n  _id,\n  titulo,\n  contenido,\n  slug,\n  fechaPublicacion,\n  imagen\n}": QueryResult;
    "*[_type == \"publicacion\" && defined(slug.current) && (\n  $lastDate == null || \n  fechaPublicacion < $lastDate || \n  (fechaPublicacion == $lastDate && _id < $lastId)\n)]|order(fechaPublicacion desc, _id desc)[0...$limit]{\n  _id,\n  titulo,\n  slug,\n  fechaPublicacion,\n  imagen,\n  extracto\n}": QueryPostsResult;
    "*[_type == \"proyecto\" && slug.current == $slug][0]{\n  _id,\n  title,\n  location,\n  description,\n  date,\n  categories,\n  gallery,\n  videoUrl\n}": QueryProjectResult;
    "*[_type == \"proyecto\" && (\n  $lastDate == null || \n  fechaPublicacion < $lastDate || \n  (fechaPublicacion == $lastDate && _id < $lastId)\n)]|order(fechaPublicacion desc, _id desc)[0...$limit]{\n  _id,\n  title,\n  slug,\n  location,\n  date,\n  gallery,\n  fechaPublicacion\n}": QueryProjectsResult;
  }
}

